---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       ROM_URL: https://udomain.dl.sourceforge.net/project/xyzuan/xd_lavender/xd_rev1.3.redwhite.OBT-lavender-20210817-0139.zip
       ROM_NAME: Generic
       TZ: Asia/Jakarta
       MIR: wet
       ZIP_NAME: xdroid1.3
  commands:
  - bash build.sh
