---
kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: Start syncing && Compiling
  image: brock5555/recovery
  environment:
       ROM_URL: https://liquidtelecom.dl.sourceforge.net/project/rayrzy/ResurrectionRemix/RROS-Q-8.7.2-20210824-rosy-Unofficial.zip
       ROM_NAME: Generic
       TZ: Asia/Jakarta
       MIR: wet
       ZIP_NAME: RROS-Q
  commands:
  - bash build.sh
